# Generated by Django 3.1.7 on 2021-03-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('git_api', '0002_auto_20210304_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullrequest',
            name='avatar_url',
            field=models.CharField(default='https://cdn4.iconfinder.com/data/icons/avatars-xmas-giveaway/128/batman_hero_avatar_comics-512.png', max_length=200),
        ),
    ]
